[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "pandas",
    "matplotlib",
    "seaborn",
    "openai==0.28"
]
