[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
description = "A script for advanced dataset analysis"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "matplotlib",
    "seaborn",
    "openai==0.28",
    "scipy",
]
